// Generated by tools/assets/gen_module.py from assets/manifest.ch01.json. Do not edit by hand.
// Runtime WebP cut from the approved Chapter 1 production sheets (lossless masters sit next to each file).
import a0 from '../../assets/chapter-01/backgrounds/ch01_bg_beach_right.webp';
import a1 from '../../assets/chapter-01/backgrounds/ch01_bg_hillside_terraces.webp';
import a2 from '../../assets/chapter-01/backgrounds/ch01_bg_hillside_terraces_b.webp';
import a3 from '../../assets/chapter-01/backgrounds/ch01_bg_islands_blue.webp';
import a4 from '../../assets/chapter-01/backgrounds/ch01_bg_outcrop_left.webp';
import a5 from '../../assets/chapter-01/backgrounds/ch01_bg_outcrop_left_b.webp';
import a6 from '../../assets/chapter-01/backgrounds/ch01_bg_rock_in_water.webp';
import a7 from '../../assets/chapter-01/backgrounds/ch01_bg_settlement.webp';
import a8 from '../../assets/chapter-01/backgrounds/ch01_bg_shore_far.webp';
import a9 from '../../assets/chapter-01/backgrounds/ch01_bg_shore_olive_tree.webp';
import a10 from '../../assets/chapter-01/props/ch01_prop_crete_island_palace.webp';
import a11 from '../../assets/chapter-01/props/ch01_prop_mycenae_citadel.webp';
import a12 from '../../assets/global/costumes/chiton_plain.webp';
import a13 from '../../assets/global/costumes/chiton_sailor_skirt.webp';
import a14 from '../../assets/global/costumes/chiton_sailor_torso.webp';
import a15 from '../../assets/global/costumes/chiton_villager_skirt.webp';
import a16 from '../../assets/global/costumes/chiton_villager_torso.webp';
import a17 from '../../assets/global/costumes/chiton_youth_skirt.webp';
import a18 from '../../assets/global/costumes/chiton_youth_torso.webp';
import a19 from '../../assets/global/costumes/cloak_long_rest.webp';
import a20 from '../../assets/global/costumes/himation_drape.webp';
import a21 from '../../assets/global/costumes/himation_elite_skirt.webp';
import a22 from '../../assets/global/costumes/himation_elite_torso.webp';
import a23 from '../../assets/global/costumes/himation_merchant_skirt.webp';
import a24 from '../../assets/global/costumes/himation_merchant_torso.webp';
import a25 from '../../assets/global/costumes/peplos_villager_skirt.webp';
import a26 from '../../assets/global/costumes/peplos_villager_torso.webp';
import a27 from '../../assets/global/environment/agave.webp';
import a28 from '../../assets/global/environment/grass_tufts_a.webp';
import a29 from '../../assets/global/environment/ground_sand_tile.webp';
import a30 from '../../assets/global/environment/house_white_a.webp';
import a31 from '../../assets/global/environment/house_white_b.webp';
import a32 from '../../assets/global/environment/house_white_c.webp';
import a33 from '../../assets/global/environment/island_a.webp';
import a34 from '../../assets/global/environment/island_b.webp';
import a35 from '../../assets/global/environment/island_c.webp';
import a36 from '../../assets/global/environment/island_d.webp';
import a37 from '../../assets/global/environment/island_e.webp';
import a38 from '../../assets/global/environment/island_f.webp';
import a39 from '../../assets/global/environment/island_g.webp';
import a40 from '../../assets/global/environment/island_h.webp';
import a41 from '../../assets/global/environment/mountains_far_soft.webp';
import a42 from '../../assets/global/environment/rock_a.webp';
import a43 from '../../assets/global/environment/rock_b.webp';
import a44 from '../../assets/global/environment/rock_c.webp';
import a45 from '../../assets/global/environment/sea_band_far.webp';
import a46 from '../../assets/global/environment/sea_tile_base.webp';
import a47 from '../../assets/global/environment/ship_boat_small.webp';
import a48 from '../../assets/global/environment/ship_merchant.webp';
import a49 from '../../assets/global/environment/shrub_a.webp';
import a50 from '../../assets/global/environment/shrub_b.webp';
import a51 from '../../assets/global/environment/shrub_c.webp';
import a52 from '../../assets/global/environment/tree_cypress_small.webp';
import a53 from '../../assets/global/environment/tree_cypress_tall.webp';
import a54 from '../../assets/global/environment/tree_olive_b_small.webp';
import a55 from '../../assets/global/environment/tree_olive_large.webp';
import a56 from '../../assets/global/environment/tree_olive_medium.webp';
import a57 from '../../assets/global/environment/tree_olive_small.webp';
import a58 from '../../assets/global/environment/village_cluster_a.webp';
import a59 from '../../assets/global/fx/birds_gull_sheet.webp';
import a60 from '../../assets/global/fx/cloud_cumulus_01.webp';
import a61 from '../../assets/global/fx/cloud_cumulus_02.webp';
import a62 from '../../assets/global/fx/cloud_cumulus_03.webp';
import a63 from '../../assets/global/fx/cloud_cumulus_04.webp';
import a64 from '../../assets/global/fx/cloud_cumulus_05.webp';
import a65 from '../../assets/global/fx/cloud_cumulus_06.webp';
import a66 from '../../assets/global/fx/cloud_cumulus_07.webp';
import a67 from '../../assets/global/fx/cloud_cumulus_08.webp';
import a68 from '../../assets/global/fx/cloud_cumulus_09.webp';
import a69 from '../../assets/global/fx/dust_puff_01.webp';
import a70 from '../../assets/global/fx/foliage_overlay.webp';
import a71 from '../../assets/global/fx/gull_01.webp';
import a72 from '../../assets/global/fx/gull_02.webp';
import a73 from '../../assets/global/fx/gull_03.webp';
import a74 from '../../assets/global/fx/gull_04.webp';
import a75 from '../../assets/global/fx/gull_05.webp';
import a76 from '../../assets/global/fx/gull_06.webp';
import a77 from '../../assets/global/fx/smoke_column_01.webp';
import a78 from '../../assets/global/fx/smoke_puff_01.webp';
import a79 from '../../assets/global/fx/smoke_puff_02.webp';
import a80 from '../../assets/global/fx/water_highlights.webp';
import a81 from '../../assets/global/fx/wave_overlay.webp';
import a82 from '../../assets/global/heads/beard_long.webp';
import a83 from '../../assets/global/heads/hair_curls.webp';
import a84 from '../../assets/global/heads/hair_short.webp';
import a85 from '../../assets/global/heads/hat_hood.webp';
import a86 from '../../assets/global/heads/hat_petasos.webp';
import a87 from '../../assets/global/heads/head_neutral.webp';
import a88 from '../../assets/global/heads/headband.webp';
import a89 from '../../assets/global/heads/helmet_corinthian.webp';
import a90 from '../../assets/global/heads/veil.webp';
import a91 from '../../assets/global/props/held/amphora_a.webp';
import a92 from '../../assets/global/props/held/amphora_b.webp';
import a93 from '../../assets/global/props/held/basket_produce.webp';
import a94 from '../../assets/global/props/held/lyre.webp';
import a95 from '../../assets/global/props/held/olive_branch.webp';
import a96 from '../../assets/global/props/held/rope.webp';
import a97 from '../../assets/global/props/held/scroll_bundle.webp';
import a98 from '../../assets/global/props/held/shield_round.webp';
import a99 from '../../assets/global/props/held/spear.webp';
import a100 from '../../assets/global/props/held/staff.webp';
import a101 from '../../assets/global/props/held/tools.webp';
import a102 from '../../assets/global/props/held/torch.webp';
import a103 from '../../assets/global/props/set/bench_wood.webp';
import a104 from '../../assets/global/props/set/crate.webp';
import a105 from '../../assets/global/props/set/fishing_net.webp';
import a106 from '../../assets/global/props/set/pithos.webp';
import a107 from '../../assets/global/rig/body_foot_sandal.webp';
import a108 from '../../assets/global/rig/body_forearm.webp';
import a109 from '../../assets/global/rig/body_head.webp';
import a110 from '../../assets/global/rig/body_master_neutral.webp';
import a111 from '../../assets/global/rig/body_shin.webp';
import a112 from '../../assets/global/rig/body_thigh.webp';
import a113 from '../../assets/global/rig/body_torso.webp';
import a114 from '../../assets/global/rig/body_upper_arm.webp';

export const LIB = {
  ch01_bg_beach_right: { src: a0, w: 586, h: 250, path: 'chapter-01/backgrounds/ch01_bg_beach_right', an: {"base":[0.4655,1.0269]} },
  ch01_bg_hillside_terraces: { src: a1, w: 750, h: 290, path: 'chapter-01/backgrounds/ch01_bg_hillside_terraces', an: {"base":[0.489,0.9896]} },
  ch01_bg_hillside_terraces_b: { src: a2, w: 544, h: 273, path: 'chapter-01/backgrounds/ch01_bg_hillside_terraces_b', an: {"base":[0.6212,0.967]} },
  ch01_bg_islands_blue: { src: a3, w: 1003, h: 216, path: 'chapter-01/backgrounds/ch01_bg_islands_blue' },
  ch01_bg_outcrop_left: { src: a4, w: 600, h: 283, path: 'chapter-01/backgrounds/ch01_bg_outcrop_left' },
  ch01_bg_outcrop_left_b: { src: a5, w: 699, h: 221, path: 'chapter-01/backgrounds/ch01_bg_outcrop_left_b' },
  ch01_bg_rock_in_water: { src: a6, w: 527, h: 216, path: 'chapter-01/backgrounds/ch01_bg_rock_in_water' },
  ch01_bg_settlement: { src: a7, w: 648, h: 219, path: 'chapter-01/backgrounds/ch01_bg_settlement' },
  ch01_bg_shore_far: { src: a8, w: 1001, h: 183, path: 'chapter-01/backgrounds/ch01_bg_shore_far' },
  ch01_bg_shore_olive_tree: { src: a9, w: 376, h: 240, path: 'chapter-01/backgrounds/ch01_bg_shore_olive_tree' },
  ch01_prop_crete_island_palace: { src: a10, w: 767, h: 316, path: 'chapter-01/props/ch01_prop_crete_island_palace', an: {"palace":[0.4927,0.1848]} },
  ch01_prop_mycenae_citadel: { src: a11, w: 674, h: 319, path: 'chapter-01/props/ch01_prop_mycenae_citadel', an: {"gate":[0.5028,0.1976]} },
  chiton_plain: { src: a12, w: 62, h: 154, path: 'global/costumes/chiton_plain' },
  chiton_sailor_skirt: { src: a13, w: 138, h: 320, path: 'global/costumes/chiton_sailor_skirt', an: {"hem":[0.5399,0.9844],"neck":[0.5399,0.025],"shoulderL":[0.2536,0.0688],"shoulderR":[0.8261,0.0688],"waist":[0.5399,0.425]} },
  chiton_sailor_torso: { src: a14, w: 138, h: 320, path: 'global/costumes/chiton_sailor_torso', an: {"hem":[0.5399,0.9844],"neck":[0.5399,0.025],"shoulderL":[0.2536,0.0688],"shoulderR":[0.8261,0.0688],"waist":[0.5399,0.425]} },
  chiton_villager_skirt: { src: a15, w: 112, h: 286, path: 'global/costumes/chiton_villager_skirt', an: {"hem":[0.4554,0.9825],"neck":[0.4554,0.0175],"shoulderL":[0.1161,0.0664],"shoulderR":[0.7946,0.0664],"waist":[0.4554,0.4196]} },
  chiton_villager_torso: { src: a16, w: 112, h: 286, path: 'global/costumes/chiton_villager_torso', an: {"hem":[0.4554,0.9825],"neck":[0.4554,0.0175],"shoulderL":[0.1161,0.0664],"shoulderR":[0.7946,0.0664],"waist":[0.4554,0.4196]} },
  chiton_youth_skirt: { src: a17, w: 101, h: 251, path: 'global/costumes/chiton_youth_skirt', an: {"hem":[0.4851,0.9761],"neck":[0.4851,0.0438],"shoulderL":[0.2475,0.0996],"shoulderR":[0.7228,0.0996],"waist":[0.4851,0.4343]} },
  chiton_youth_torso: { src: a18, w: 101, h: 251, path: 'global/costumes/chiton_youth_torso', an: {"hem":[0.4851,0.9761],"neck":[0.4851,0.0438],"shoulderL":[0.2475,0.0996],"shoulderR":[0.7228,0.0996],"waist":[0.4851,0.4343]} },
  cloak_long_rest: { src: a19, w: 124, h: 154, path: 'global/costumes/cloak_long_rest', an: {"collar":[0.4516,-0.0162]} },
  himation_drape: { src: a20, w: 100, h: 181, path: 'global/costumes/himation_drape' },
  himation_elite_skirt: { src: a21, w: 157, h: 303, path: 'global/costumes/himation_elite_skirt', an: {"hem":[0.5892,0.9868],"neck":[0.5892,0.0363],"shoulderL":[0.3694,0.0825],"shoulderR":[0.8089,0.0825],"waist":[0.5892,0.4323]} },
  himation_elite_torso: { src: a22, w: 157, h: 303, path: 'global/costumes/himation_elite_torso', an: {"hem":[0.5892,0.9868],"neck":[0.5892,0.0363],"shoulderL":[0.3694,0.0825],"shoulderR":[0.8089,0.0825],"waist":[0.5892,0.4323]} },
  himation_merchant_skirt: { src: a23, w: 189, h: 330, path: 'global/costumes/himation_merchant_skirt', an: {"hem":[0.6508,0.9818],"neck":[0.6508,0.0485],"shoulderL":[0.3757,0.0909],"shoulderR":[0.9259,0.0909],"waist":[0.6508,0.4394]} },
  himation_merchant_torso: { src: a24, w: 189, h: 330, path: 'global/costumes/himation_merchant_torso', an: {"hem":[0.6508,0.9818],"neck":[0.6508,0.0485],"shoulderL":[0.3757,0.0909],"shoulderR":[0.9259,0.0909],"waist":[0.6508,0.4394]} },
  peplos_villager_skirt: { src: a25, w: 123, h: 316, path: 'global/costumes/peplos_villager_skirt', an: {"hem":[0.4634,0.9873],"neck":[0.4634,0.0222],"shoulderL":[0.252,0.0665],"shoulderR":[0.6748,0.0665],"waist":[0.4634,0.4272]} },
  peplos_villager_torso: { src: a26, w: 123, h: 316, path: 'global/costumes/peplos_villager_torso', an: {"hem":[0.4634,0.9873],"neck":[0.4634,0.0222],"shoulderL":[0.252,0.0665],"shoulderR":[0.6748,0.0665],"waist":[0.4634,0.4272]} },
  agave: { src: a27, w: 320, h: 368, path: 'global/environment/agave' },
  grass_tufts_a: { src: a28, w: 258, h: 193, path: 'global/environment/grass_tufts_a' },
  ground_sand_tile: { src: a29, w: 1280, h: 320, path: 'global/environment/ground_sand_tile' },
  house_white_a: { src: a30, w: 336, h: 258, path: 'global/environment/house_white_a' },
  house_white_b: { src: a31, w: 402, h: 305, path: 'global/environment/house_white_b' },
  house_white_c: { src: a32, w: 534, h: 305, path: 'global/environment/house_white_c' },
  island_a: { src: a33, w: 413, h: 56, path: 'global/environment/island_a' },
  island_b: { src: a34, w: 165, h: 38, path: 'global/environment/island_b' },
  island_c: { src: a35, w: 574, h: 74, path: 'global/environment/island_c' },
  island_d: { src: a36, w: 674, h: 94, path: 'global/environment/island_d' },
  island_e: { src: a37, w: 174, h: 33, path: 'global/environment/island_e' },
  island_f: { src: a38, w: 132, h: 26, path: 'global/environment/island_f' },
  island_g: { src: a39, w: 214, h: 33, path: 'global/environment/island_g' },
  island_h: { src: a40, w: 587, h: 93, path: 'global/environment/island_h' },
  mountains_far_soft: { src: a41, w: 2048, h: 64, path: 'global/environment/mountains_far_soft' },
  rock_a: { src: a42, w: 648, h: 215, path: 'global/environment/rock_a' },
  rock_b: { src: a43, w: 270, h: 158, path: 'global/environment/rock_b' },
  rock_c: { src: a44, w: 390, h: 269, path: 'global/environment/rock_c' },
  sea_band_far: { src: a45, w: 902, h: 144, path: 'global/environment/sea_band_far' },
  sea_tile_base: { src: a46, w: 3072, h: 80, path: 'global/environment/sea_tile_base' },
  ship_boat_small: { src: a47, w: 459, h: 429, path: 'global/environment/ship_boat_small', an: {"water":[0.5098,0.9557]} },
  ship_merchant: { src: a48, w: 670, h: 515, path: 'global/environment/ship_merchant', an: {"mast":[0.4866,0.1417],"water":[0.4985,0.9573]} },
  shrub_a: { src: a49, w: 311, h: 173, path: 'global/environment/shrub_a' },
  shrub_b: { src: a50, w: 246, h: 192, path: 'global/environment/shrub_b' },
  shrub_c: { src: a51, w: 177, h: 192, path: 'global/environment/shrub_c' },
  tree_cypress_small: { src: a52, w: 100, h: 309, path: 'global/environment/tree_cypress_small' },
  tree_cypress_tall: { src: a53, w: 121, h: 442, path: 'global/environment/tree_cypress_tall', an: {"base":[0.438,0.9977]} },
  tree_olive_b_small: { src: a54, w: 335, h: 269, path: 'global/environment/tree_olive_b_small' },
  tree_olive_large: { src: a55, w: 473, h: 423, path: 'global/environment/tree_olive_large', an: {"base":[0.3975,0.9764]} },
  tree_olive_medium: { src: a56, w: 537, h: 412, path: 'global/environment/tree_olive_medium', an: {"base":[0.4525,0.9684]} },
  tree_olive_small: { src: a57, w: 328, h: 290, path: 'global/environment/tree_olive_small' },
  village_cluster_a: { src: a58, w: 486, h: 274, path: 'global/environment/village_cluster_a' },
  birds_gull_sheet: { src: a59, w: 211, h: 161, path: 'global/fx/birds_gull_sheet' },
  cloud_cumulus_01: { src: a60, w: 124, h: 30, path: 'global/fx/cloud_cumulus_01' },
  cloud_cumulus_02: { src: a61, w: 92, h: 16, path: 'global/fx/cloud_cumulus_02' },
  cloud_cumulus_03: { src: a62, w: 132, h: 37, path: 'global/fx/cloud_cumulus_03' },
  cloud_cumulus_04: { src: a63, w: 196, h: 58, path: 'global/fx/cloud_cumulus_04' },
  cloud_cumulus_05: { src: a64, w: 106, h: 43, path: 'global/fx/cloud_cumulus_05' },
  cloud_cumulus_06: { src: a65, w: 121, h: 42, path: 'global/fx/cloud_cumulus_06' },
  cloud_cumulus_07: { src: a66, w: 84, h: 34, path: 'global/fx/cloud_cumulus_07' },
  cloud_cumulus_08: { src: a67, w: 166, h: 66, path: 'global/fx/cloud_cumulus_08' },
  cloud_cumulus_09: { src: a68, w: 191, h: 76, path: 'global/fx/cloud_cumulus_09' },
  dust_puff_01: { src: a69, w: 294, h: 168, path: 'global/fx/dust_puff_01' },
  foliage_overlay: { src: a70, w: 290, h: 329, path: 'global/fx/foliage_overlay' },
  gull_01: { src: a71, w: 85, h: 28, path: 'global/fx/gull_01' },
  gull_02: { src: a72, w: 54, h: 27, path: 'global/fx/gull_02' },
  gull_03: { src: a73, w: 71, h: 23, path: 'global/fx/gull_03' },
  gull_04: { src: a74, w: 67, h: 22, path: 'global/fx/gull_04' },
  gull_05: { src: a75, w: 63, h: 18, path: 'global/fx/gull_05' },
  gull_06: { src: a76, w: 58, h: 21, path: 'global/fx/gull_06' },
  smoke_column_01: { src: a77, w: 174, h: 227, path: 'global/fx/smoke_column_01' },
  smoke_puff_01: { src: a78, w: 135, h: 152, path: 'global/fx/smoke_puff_01' },
  smoke_puff_02: { src: a79, w: 118, h: 174, path: 'global/fx/smoke_puff_02' },
  water_highlights: { src: a80, w: 356, h: 149, path: 'global/fx/water_highlights' },
  wave_overlay: { src: a81, w: 129, h: 104, path: 'global/fx/wave_overlay' },
  beard_long: { src: a82, w: 161, h: 255, path: 'global/heads/beard_long', an: {"neck":[0.4907,0.7294],"skull":[0.4981,0.4031]}, skull: 0.795 },
  hair_curls: { src: a83, w: 193, h: 265, path: 'global/heads/hair_curls', an: {"neck":[0.4352,0.7675],"skull":[0.4922,0.434]}, skull: 0.7047 },
  hair_short: { src: a84, w: 183, h: 278, path: 'global/heads/hair_short', an: {"neck":[0.3989,0.746],"skull":[0.5038,0.4281]}, skull: 0.7432 },
  hat_hood: { src: a85, w: 193, h: 268, path: 'global/heads/hat_hood', an: {"neck":[0.5648,0.7731],"skull":[0.6684,0.4433]}, skull: 0.7047 },
  hat_petasos: { src: a86, w: 229, h: 298, path: 'global/heads/hat_petasos', an: {"neck":[0.4323,0.7342],"skull":[0.421,0.4376]}, skull: 0.5939 },
  head_neutral: { src: a87, w: 151, h: 261, path: 'global/heads/head_neutral', an: {"neck":[0.404,0.6529],"skull":[0.502,0.3142]}, skull: 0.9007 },
  headband: { src: a88, w: 162, h: 271, path: 'global/heads/headband', an: {"neck":[0.4198,0.6657],"skull":[0.4877,0.3395]}, skull: 0.8395 },
  helmet_corinthian: { src: a89, w: 203, h: 360, path: 'global/heads/helmet_corinthian', an: {"neck":[0.6601,0.7233],"skull":[0.5951,0.4778]}, skull: 0.67 },
  veil: { src: a90, w: 220, h: 287, path: 'global/heads/veil', an: {"neck":[0.5909,0.708],"skull":[0.7182,0.4]}, skull: 0.6182 },
  amphora_a: { src: a91, w: 95, h: 131, path: 'global/props/held/amphora_a' },
  amphora_b: { src: a92, w: 94, h: 127, path: 'global/props/held/amphora_b' },
  basket_produce: { src: a93, w: 117, h: 107, path: 'global/props/held/basket_produce' },
  lyre: { src: a94, w: 86, h: 109, path: 'global/props/held/lyre' },
  olive_branch: { src: a95, w: 137, h: 101, path: 'global/props/held/olive_branch' },
  rope: { src: a96, w: 139, h: 98, path: 'global/props/held/rope' },
  scroll_bundle: { src: a97, w: 157, h: 94, path: 'global/props/held/scroll_bundle' },
  shield_round: { src: a98, w: 117, h: 119, path: 'global/props/held/shield_round' },
  spear: { src: a99, w: 133, h: 94, path: 'global/props/held/spear' },
  staff: { src: a100, w: 39, h: 379, path: 'global/props/held/staff', an: {"bottom":[0.5641,1.0079],"top":[0.7692,0.0158]} },
  tools: { src: a101, w: 61, h: 118, path: 'global/props/held/tools' },
  torch: { src: a102, w: 55, h: 119, path: 'global/props/held/torch' },
  bench_wood: { src: a103, w: 204, h: 80, path: 'global/props/set/bench_wood' },
  crate: { src: a104, w: 128, h: 108, path: 'global/props/set/crate' },
  fishing_net: { src: a105, w: 209, h: 144, path: 'global/props/set/fishing_net' },
  pithos: { src: a106, w: 80, h: 114, path: 'global/props/set/pithos' },
  body_foot_sandal: { src: a107, w: 48, h: 43, path: 'global/rig/body_foot_sandal' },
  body_forearm: { src: a108, w: 26, h: 71, path: 'global/rig/body_forearm' },
  body_head: { src: a109, w: 54, h: 85, path: 'global/rig/body_head' },
  body_master_neutral: { src: a110, w: 130, h: 296, path: 'global/rig/body_master_neutral' },
  body_shin: { src: a111, w: 16, h: 76, path: 'global/rig/body_shin' },
  body_thigh: { src: a112, w: 17, h: 76, path: 'global/rig/body_thigh' },
  body_torso: { src: a113, w: 62, h: 212, path: 'global/rig/body_torso' },
  body_upper_arm: { src: a114, w: 32, h: 65, path: 'global/rig/body_upper_arm' },
};
