// Generated by tools/assets/gen_module.py from assets/library.json + assets/plates.json. Do not edit by hand.
// Runtime WebP for the production assets generated per asset (see assets/_generated and README).
import a0 from '../../assets/global/characters/char_elder_full.webp';
import a1 from '../../assets/global/characters/char_farmer_full.webp';
import a2 from '../../assets/global/characters/char_foot_sandal.webp';
import a3 from '../../assets/global/characters/char_hand_grip.webp';
import a4 from '../../assets/global/characters/char_hand_open.webp';
import a5 from '../../assets/global/characters/char_water_carrier_full.webp';
import a6 from '../../assets/global/costumes/costume_chiton_farmer.webp';
import a7 from '../../assets/global/costumes/costume_exomis_worker.webp';
import a8 from '../../assets/global/costumes/costume_himation_elder.webp';
import a9 from '../../assets/global/costumes/costume_himation_trader.webp';
import a10 from '../../assets/global/costumes/costume_peplos.webp';
import a11 from '../../assets/global/costumes/costume_tunic_child.webp';
import a12 from '../../assets/global/environment/env_agave_a.webp';
import a13 from '../../assets/global/environment/env_cloud_a.webp';
import a14 from '../../assets/global/environment/env_cloud_b.webp';
import a15 from '../../assets/global/environment/env_cloud_c.webp';
import a16 from '../../assets/global/environment/env_cypress_a.webp';
import a17 from '../../assets/global/environment/env_fg_grass_clump.webp';
import a18 from '../../assets/global/environment/env_fg_olive_branch.webp';
import a19 from '../../assets/global/environment/env_olive_sapling_1.webp';
import a20 from '../../assets/global/environment/env_olive_sapling_2.webp';
import a21 from '../../assets/global/environment/env_olive_sapling_3.webp';
import a22 from '../../assets/global/environment/env_olive_tree_a.webp';
import a23 from '../../assets/global/environment/env_rock_a.webp';
import a24 from '../../assets/global/environment/env_shrub_a.webp';
import a25 from '../../assets/global/fx/fx_gull_down.webp';
import a26 from '../../assets/global/fx/fx_gull_up.webp';
import a27 from '../../assets/global/fx/fx_smoke_a.webp';
import a28 from '../../assets/global/fx/fx_smoke_b.webp';
import a29 from '../../assets/global/heads/head_bun_headband.webp';
import a30 from '../../assets/global/heads/head_child_curls.webp';
import a31 from '../../assets/global/heads/head_elder_beard.webp';
import a32 from '../../assets/global/heads/head_petasos.webp';
import a33 from '../../assets/global/heads/head_trader_curls_beard.webp';
import a34 from '../../assets/global/heads/head_worker_headband.webp';
import a35 from '../../assets/global/props/prop_amphora_a.webp';
import a36 from '../../assets/global/props/prop_basket_produce.webp';
import a37 from '../../assets/global/props/prop_crate.webp';
import a38 from '../../assets/global/props/prop_fishing_net.webp';
import a39 from '../../assets/global/props/prop_pithos.webp';
import a40 from '../../assets/global/props/prop_staff.webp';
import a41 from '../../assets/global/ships/ship_fishing_boat.webp';
import a42 from '../../assets/global/ships/ship_merchant.webp';
import a43 from '../../assets/global/ships/ship_merchant_sail.webp';
import a44 from '../../assets/global/ships/ship_small_sail.webp';
import a45 from '../../assets/chapter-01/ch01_env.webp';
import a46 from '../../assets/chapter-01/ch01_sea_mask.webp';
import a47 from '../../assets/intro/intro_env.webp';
import a48 from '../../assets/intro/intro_sea_mask.webp';

export const LIB = {
  char_elder_full: { src: a0, w: 166, h: 600, an: {"base":[0.4035,0.9936]} },
  char_farmer_full: { src: a1, w: 169, h: 600, an: {"base":[0.3785,0.9937]} },
  char_foot_sandal: { src: a2, w: 120, h: 96, an: {"ankle":[0.2172,0.0164],"sole":[0.618,0.9766]} },
  char_hand_grip: { src: a3, w: 35, h: 64, an: {"wrist":[0.3927,0.0175]} },
  char_hand_open: { src: a4, w: 31, h: 64, an: {"wrist":[0.371,0.0173]} },
  char_water_carrier_full: { src: a5, w: 158, h: 600, an: {"base":[0.411,0.9935]} },
  costume_chiton_farmer: { src: a6, w: 203, h: 460, an: {"armhole":[0.22,0.12],"collar":[0.4763,0.0077],"hem":[0.5175,0.9912],"shoulderF":[0.66,0.07]}, upx: 0.16394, armholeR: [0.045, 0.07] },
  costume_exomis_worker: { src: a7, w: 225, h: 460, an: {"armhole":[0.265,0.17],"collar":[0.4835,0.0075],"hem":[0.5077,0.9914],"shoulderF":[0.7,0.09]}, upx: 0.15895, armholeR: [0.06, 0.11] },
  costume_himation_elder: { src: a8, w: 154, h: 460, an: {"armhole":[0.18,0.12],"collar":[0.4247,0.0066],"hem":[0.4506,0.9934],"shoulderF":[0.62,0.07]}, upx: 0.21881, armholeR: [0.055, 0.08] },
  costume_himation_trader: { src: a9, w: 210, h: 460, an: {"armhole":[0.175,0.18],"collar":[0.3922,0.0071],"hem":[0.4578,0.9919],"shoulderF":[0.66,0.1]}, upx: 0.16843, armholeR: [0.065, 0.115] },
  costume_peplos: { src: a10, w: 153, h: 460, an: {"armhole":[0.195,0.13],"collar":[0.4618,0.0066],"hem":[0.4828,0.9934],"shoulderF":[0.66,0.08]}, upx: 0.22078, armholeR: [0.06, 0.085] },
  costume_tunic_child: { src: a11, w: 231, h: 460, an: {"armhole":[0.18,0.17],"collar":[0.4885,0.009],"hem":[0.4949,0.9897],"shoulderF":[0.68,0.1]}, upx: 0.13338, armholeR: [0.07, 0.12] },
  env_agave_a: { src: a12, w: 560, h: 513, an: {"base":[0.4735,0.9881]} },
  env_cloud_a: { src: a13, w: 1000, h: 328, an: {"base":[0.3741,0.9815]} },
  env_cloud_b: { src: a14, w: 947, h: 291, an: {"base":[0.5185,0.9725]} },
  env_cloud_c: { src: a15, w: 1000, h: 221, an: {"base":[0.32,0.9752]} },
  env_cypress_a: { src: a16, w: 139, h: 560, an: {"base":[0.4845,0.9938]} },
  env_fg_grass_clump: { src: a17, w: 444, h: 900, an: {"base":[0.657,0.9992]} },
  env_fg_olive_branch: { src: a18, w: 513, h: 900, an: {"top":[0.3844,0.0]} },
  env_olive_sapling_1: { src: a19, w: 149, h: 160, an: {"base":[0.4656,0.9778]} },
  env_olive_sapling_2: { src: a20, w: 78, h: 160, an: {"base":[0.4937,0.9901]} },
  env_olive_sapling_3: { src: a21, w: 80, h: 160, an: {"base":[0.4589,0.9931]} },
  env_olive_tree_a: { src: a22, w: 560, h: 501, an: {"base":[0.5185,0.993]} },
  env_rock_a: { src: a23, w: 560, h: 368, an: {"base":[0.485,0.9798]} },
  env_shrub_a: { src: a24, w: 560, h: 481, an: {"base":[0.5881,0.9861]} },
  fx_gull_down: { src: a25, w: 120, h: 89, an: {"base":[0.9667,0.9663]} },
  fx_gull_up: { src: a26, w: 89, h: 120, an: {"base":[0.1274,0.9787]} },
  fx_smoke_a: { src: a27, w: 56, h: 260, an: {"base":[0.4318,0.9716]} },
  fx_smoke_b: { src: a28, w: 94, h: 260, an: {"base":[0.5161,0.97]} },
  head_bun_headband: { src: a29, w: 220, h: 215, an: {"neck":[0.5765,0.9719]}, upx: 0.15323 },
  head_child_curls: { src: a30, w: 168, h: 220, an: {"neck":[0.4376,0.9857]}, upx: 0.11746 },
  head_elder_beard: { src: a31, w: 183, h: 220, an: {"neck":[0.401,0.9705]}, upx: 0.14231 },
  head_petasos: { src: a32, w: 220, h: 170, an: {"neck":[0.4548,0.9745]}, upx: 0.21272 },
  head_trader_curls_beard: { src: a33, w: 175, h: 220, an: {"neck":[0.4631,0.9869]}, upx: 0.12947 },
  head_worker_headband: { src: a34, w: 167, h: 220, an: {"neck":[0.4157,0.9864]}, upx: 0.12372 },
  prop_amphora_a: { src: a35, w: 135, h: 300, an: {"base":[0.4889,0.9901]} },
  prop_basket_produce: { src: a36, w: 276, h: 300, an: {"base":[0.4807,0.9895],"handle":[0.4551,0.0092]} },
  prop_crate: { src: a37, w: 291, h: 300, an: {"base":[0.5,0.987]} },
  prop_fishing_net: { src: a38, w: 300, h: 213, an: {"base":[0.4921,0.9863]} },
  prop_pithos: { src: a39, w: 243, h: 300, an: {"base":[0.4891,0.9906]} },
  prop_staff: { src: a40, w: 31, h: 360, an: {"base":[0.5818,0.993],"top":[0.4818,0.0055]} },
  ship_fishing_boat: { src: a41, w: 360, h: 181, an: {"base":[0.5211,0.9807]} },
  ship_merchant: { src: a42, w: 900, h: 602, an: {"keel":[0.5,0.9939],"yard":[0.3359,0.1336]} },
  ship_merchant_sail: { src: a43, w: 900, h: 602, an: {"keel":[0.5,0.9939],"yard":[0.3359,0.1336]} },
  ship_small_sail: { src: a44, w: 343, h: 360, an: {"base":[0.4449,0.9905]} },
  ch01_env: { src: a45, w: 3840, h: 2288, horizon: 1356, skyExt: 640, masterH: 1648 },
  ch01_sea_mask: { src: a46, w: 3840, h: 2288, horizon: 1356, skyExt: 640, masterH: 1648 },
  intro_env: { src: a47, w: 3840, h: 2288, horizon: 1437, skyExt: 640, masterH: 1648 },
  intro_sea_mask: { src: a48, w: 3840, h: 2288, horizon: 1437, skyExt: 640, masterH: 1648 },
};
