"""Write src/art/library.gen.js from assets/manifest.ch01.json (import map + sizes + anchors)."""
import json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
man = json.load(open(os.path.join(ROOT, 'assets', 'manifest.ch01.json')))
out = os.path.join(ROOT, 'src', 'art', 'library.gen.js')
lines = ['// Generated by tools/assets/gen_module.py from assets/manifest.ch01.json. Do not edit by hand.',
         '// Runtime WebP cut from the approved Chapter 1 production sheets (lossless masters sit next to each file).']
entries = []
for i, rel in enumerate(sorted(man)):
    key = os.path.basename(rel)
    imp = os.path.relpath(os.path.join(ROOT, 'assets', rel + '.webp'), os.path.dirname(out)).replace(os.sep, '/')
    lines.append(f"import a{i} from '{imp}';")
    m = man[rel]
    extra = ''
    if m.get('anchors'): extra += ', an: ' + json.dumps(m['anchors'], separators=(',', ':'))
    if 'skull_d' in m: extra += f", skull: {m['skull_d']}"
    entries.append(f"  {key}: {{ src: a{i}, w: {m['w']}, h: {m['h']}, path: '{rel}'{extra} }},")
lines.append('')
lines.append('export const LIB = {')
lines += entries
lines.append('};')
open(out, 'w').write('\n'.join(lines) + '\n')
print(out, len(entries))
