"""Write src/art/library.gen.js from assets/library.json and assets/plates.json (import map + sizes + anchors)."""
import json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
lib = json.load(open(os.path.join(ROOT, 'assets', 'library.json')))
plates = json.load(open(os.path.join(ROOT, 'assets', 'plates.json')))
out = os.path.join(ROOT, 'src', 'art', 'library.gen.js')
rel = lambda p: os.path.relpath(os.path.join(ROOT, 'assets', p), os.path.dirname(out)).replace(os.sep, '/')
lines = ['// Generated by tools/assets/gen_module.py from assets/library.json + assets/plates.json. Do not edit by hand.',
         '// Runtime WebP for the production assets generated per asset (see assets/_generated and README).']
entries, i = [], 0
for path in sorted(lib):
    m = lib[path]
    key = os.path.basename(path)
    lines.append(f"import a{i} from '{rel(path + '.webp')}';")
    extra = ''
    if m.get('anchors'): extra += ', an: ' + json.dumps(m['anchors'], separators=(',', ':'))
    if 'upx' in m: extra += f", upx: {m['upx']}"
    entries.append(f"  {key}: {{ src: a{i}, w: {m['w']}, h: {m['h']}{extra} }},")
    i += 1
PL = [('ch01_env', 'chapter-01/ch01_env_world.webp', 'ch01'), ('ch01_sea_mask', 'chapter-01/ch01_sea_mask.webp', 'ch01'),
      ('intro_env', 'intro/intro_env.webp', 'intro'), ('intro_sea_mask', 'intro/intro_sea_mask.webp', 'intro')]
for key, p, grp in PL:
    m = plates[grp]
    lines.append(f"import a{i} from '{rel(p)}';")
    entries.append(f"  {key}: {{ src: a{i}, w: {m['w']}, h: {m['h']}, horizon: {m['horizon']} }},")
    i += 1
lines += ['', 'export const LIB = {'] + entries + ['};']
open(out, 'w').write('\n'.join(lines) + '\n')
print(out, len(entries))
